"""Utilities for normalising country data from the WarEra API."""

# Static list of all 173 countries in WarEra (used for autocomplete).
ALL_COUNTRY_NAMES: list[str] = [
    "Afghanistan",
    "Albania",
    "Algeria",
    "Angola",
    "Argentina",
    "Armenia",
    "Australia",
    "Austria",
    "Azerbaijan",
    "Bahamas",
    "Bangladesh",
    "Belarus",
    "Belgium",
    "Belize",
    "Benin",
    "Bhutan",
    "Bolivia",
    "Bosnia",
    "Botswana",
    "Brazil",
    "Brunei",
    "Bulgaria",
    "Burkina Faso",
    "Burundi",
    "Cambodia",
    "Cameroon",
    "Canada",
    "Cape Verde",
    "Central Africa",
    "Chad",
    "Chile",
    "China",
    "Colombia",
    "Congo",
    "Costa Rica",
    "Croatia",
    "Cuba",
    "Cyprus",
    "Czechia",
    "Denmark",
    "Djibouti",
    "Dominican Republic",
    "DR Congo",
    "East Timor",
    "Ecuador",
    "Egypt",
    "El Salvador",
    "Equatorial Guinea",
    "Eritrea",
    "Estonia",
    "Eswatini",
    "Ethiopia",
    "Fiji",
    "Finland",
    "France",
    "Gabon",
    "Gambia",
    "Georgia",
    "Germany",
    "Ghana",
    "Greece",
    "Greenland",
    "Guatemala",
    "Guinea",
    "Guinea-Bissau",
    "Guyana",
    "Haiti",
    "Honduras",
    "Hungary",
    "Iceland",
    "India",
    "Indonesia",
    "Iran",
    "Iraq",
    "Ireland",
    "Israel",
    "Italy",
    "Ivory Coast",
    "Jamaica",
    "Japan",
    "Jordan",
    "Kazakhstan",
    "Kenya",
    "Kosovo",
    "Kuwait",
    "Kyrgyzstan",
    "Laos",
    "Latvia",
    "Lebanon",
    "Lesotho",
    "Liberia",
    "Libya",
    "Lithuania",
    "Luxembourg",
    "Madagascar",
    "Malawi",
    "Malaysia",
    "Mali",
    "Malta",
    "Mauritania",
    "Mexico",
    "Moldova",
    "Mongolia",
    "Montenegro",
    "Morocco",
    "Mozambique",
    "Myanmar",
    "Namibia",
    "Nepal",
    "Netherlands",
    "New Zealand",
    "Nicaragua",
    "Niger",
    "Nigeria",
    "North Korea",
    "North Macedonia",
    "Norway",
    "Oman",
    "Pakistan",
    "Palestine",
    "Panama",
    "Papua New Guinea",
    "Paraguay",
    "Peru",
    "Philippines",
    "Poland",
    "Portugal",
    "Puerto Rico",
    "Qatar",
    "Romania",
    "Russia",
    "Rwanda",
    "Saudi Arabia",
    "Senegal",
    "Serbia",
    "Sierra Leone",
    "Singapore",
    "Slovakia",
    "Slovenia",
    "Solomon Islands",
    "Somalia",
    "South Africa",
    "South Korea",
    "South Sudan",
    "Spain",
    "Sri Lanka",
    "Sudan",
    "Suriname",
    "Sweden",
    "Switzerland",
    "Syria",
    "São Tomé and Príncipe",
    "Taiwan",
    "Tajikistan",
    "Tanzania",
    "Thailand",
    "Togo",
    "Trinidad and Tobago",
    "Tunisia",
    "Turkey",
    "Turkmenistan",
    "Uganda",
    "Ukraine",
    "United Arab Emirates",
    "United Kingdom",
    "United States",
    "Uruguay",
    "Uzbekistan",
    "Vanuatu",
    "Vatican City",
    "Venezuela",
    "Vietnam",
    "Yemen",
    "Zambia",
    "Zimbabwe",
]


def extract_country_list(api_response) -> list[dict]:
    """Normalise the getAllCountries API envelope into a plain list of country dicts."""
    if isinstance(api_response, list):
        return [c for c in api_response if isinstance(c, dict)]
    if isinstance(api_response, dict):
        if isinstance(api_response.get("data"), list):
            return [c for c in api_response["data"] if isinstance(c, dict)]
        r = api_response.get("result")
        if isinstance(r, dict) and isinstance(r.get("data"), list):
            return [c for c in r["data"] if isinstance(c, dict)]
        for key in ("countries", "items"):
            v = api_response.get(key)
            if isinstance(v, list):
                return [c for c in v if isinstance(c, dict)]
    return []


_COUNTRY_ALIASES: dict[str, str] = {
    "turkey": "turkiye",
    # Dutch name → English name (lower-case both sides)
    "afghanistan": "afghanistan",
    "albanië": "albania",
    "algerije": "algeria",
    "angola": "angola",
    "argentinië": "argentina",
    "armenië": "armenia",
    "australië": "australia",
    "oostenrijk": "austria",
    "azerbeidzjan": "azerbaijan",
    "bahama's": "bahamas",
    "bangladesh": "bangladesh",
    "wit-rusland": "belarus",
    "witrusland": "belarus",
    "belgië": "belgium",
    "belgie": "belgium",
    "belize": "belize",
    "benin": "benin",
    "bhutan": "bhutan",
    "bolivia": "bolivia",
    "bosnië": "bosnia",
    "bosnie": "bosnia",
    "botswana": "botswana",
    "brazilië": "brazil",
    "brazilie": "brazil",
    "brunei": "brunei",
    "bulgarije": "bulgaria",
    "burkina faso": "burkina faso",
    "burundi": "burundi",
    "cambodja": "cambodia",
    "kameroen": "cameroon",
    "canada": "canada",
    "kaapverdië": "cape verde",
    "kaapverdie": "cape verde",
    "centraal-afrika": "central africa",
    "tsjaad": "chad",
    "chili": "chile",
    "china": "china",
    "colombia": "colombia",
    "congo": "congo",
    "costa rica": "costa rica",
    "kroatië": "croatia",
    "kroatie": "croatia",
    "cuba": "cuba",
    "cyprus": "cyprus",
    "tsjechië": "czechia",
    "tsjechie": "czechia",
    "denemarken": "denmark",
    "djibouti": "djibouti",
    "dominicaanse republiek": "dominican republic",
    "dr congo": "dr congo",
    "oost-timor": "east timor",
    "ecuador": "ecuador",
    "egypte": "egypt",
    "el salvador": "el salvador",
    "equatoriaal-guinea": "equatorial guinea",
    "eritrea": "eritrea",
    "estland": "estonia",
    "eswatini": "eswatini",
    "ethiopië": "ethiopia",
    "ethiopie": "ethiopia",
    "fiji": "fiji",
    "finland": "finland",
    "frankrijk": "france",
    "gabon": "gabon",
    "gambia": "gambia",
    "georgië": "georgia",
    "georgie": "georgia",
    "duitsland": "germany",
    "ghana": "ghana",
    "griekenland": "greece",
    "groenland": "greenland",
    "guatemala": "guatemala",
    "guinee": "guinea",
    "guinea-bissau": "guinea-bissau",
    "guyana": "guyana",
    "haïti": "haiti",
    "haití": "haiti",
    "haiti": "haiti",
    "honduras": "honduras",
    "hongarije": "hungary",
    "ijsland": "iceland",
    "india": "india",
    "indonesië": "indonesia",
    "indonesie": "indonesia",
    "iran": "iran",
    "irak": "iraq",
    "ierland": "ireland",
    "israël": "israel",
    "israel": "israel",
    "italië": "italy",
    "italie": "italy",
    "ivoorkust": "ivory coast",
    "ivoor kust": "ivory coast",
    "jamaïca": "jamaica",
    "jamaica": "jamaica",
    "japan": "japan",
    "jordanië": "jordan",
    "jordanie": "jordan",
    "kazachstan": "kazakhstan",
    "kenia": "kenya",
    "kosovo": "kosovo",
    "koeweit": "kuwait",
    "kirgizstan": "kyrgyzstan",
    "laos": "laos",
    "letland": "latvia",
    "libanon": "lebanon",
    "lesotho": "lesotho",
    "liberia": "liberia",
    "libië": "libya",
    "libie": "libya",
    "litouwen": "lithuania",
    "luxemburg": "luxembourg",
    "madagaskar": "madagascar",
    "malawi": "malawi",
    "maleisië": "malaysia",
    "maleisie": "malaysia",
    "mali": "mali",
    "malta": "malta",
    "mauritanië": "mauritania",
    "mauritanie": "mauritania",
    "mexico": "mexico",
    "moldavië": "moldova",
    "moldavie": "moldova",
    "mongolië": "mongolia",
    "mongolie": "mongolia",
    "montenegro": "montenegro",
    "marokko": "morocco",
    "mozambique": "mozambique",
    "myanmar": "myanmar",
    "namibië": "namibia",
    "namibie": "namibia",
    "nepal": "nepal",
    "nederland": "netherlands",
    "netherlands": "netherlands",
    "nieuw-zeeland": "new zealand",
    "nieuw zeeland": "new zealand",
    "nicaragua": "nicaragua",
    "niger": "niger",
    "nigeria": "nigeria",
    "noord-korea": "north korea",
    "noord korea": "north korea",
    "noord-macedonië": "north macedonia",
    "noord macedonie": "north macedonia",
    "noorwegen": "norway",
    "oman": "oman",
    "pakistan": "pakistan",
    "palestina": "palestine",
    "panama": "panama",
    "papoea-nieuw-guinea": "papua new guinea",
    "papoea nieuw guinea": "papua new guinea",
    "paraguay": "paraguay",
    "peru": "peru",
    "filipijnen": "philippines",
    "filippijnen": "philippines",
    "polen": "poland",
    "portugal": "portugal",
    "puerto rico": "puerto rico",
    "qatar": "qatar",
    "roemenië": "romania",
    "roemenie": "romania",
    "rusland": "russia",
    "rwanda": "rwanda",
    "saoedi-arabië": "saudi arabia",
    "saudi arabie": "saudi arabia",
    "senegal": "senegal",
    "servië": "serbia",
    "servie": "serbia",
    "sierra leone": "sierra leone",
    "singapore": "singapore",
    "slowakije": "slovakia",
    "slovenië": "slovenia",
    "slovenie": "slovenia",
    "salomonseilanden": "solomon islands",
    "somalië": "somalia",
    "somalie": "somalia",
    "zuid-afrika": "south africa",
    "zuid afrika": "south africa",
    "zuid-korea": "south korea",
    "zuid korea": "south korea",
    "south sudan": "south sudan",
    "soedan": "sudan",
    "suriname": "suriname",
    "zweden": "sweden",
    "zwitserland": "switzerland",
    "syrië": "syria",
    "syrie": "syria",
    "sao tomé en principe": "são tomé and príncipe",
    "sao tome": "são tomé and príncipe",
    "taiwan": "taiwan",
    "tadzjikistan": "tajikistan",
    "tanzanië": "tanzania",
    "tanzanie": "tanzania",
    "thailand": "thailand",
    "togo": "togo",
    "trinidad en tobago": "trinidad and tobago",
    "tunesië": "tunisia",
    "tunesie": "tunisia",
    "turkije": "türkiye",
    "turkmenistan": "turkmenistan",
    "oeganda": "uganda",
    "oekraïne": "ukraine",
    "oekraine": "ukraine",
    "verenigde arabische emiraten": "united arab emirates",
    "vae": "united arab emirates",
    "verenigd koninkrijk": "united kingdom",
    "vk": "united kingdom",
    "uk": "united kingdom",
    "verenigde staten": "united states",
    "vs": "united states",
    "usa": "united states",
    "uruguay": "uruguay",
    "oezbekistan": "uzbekistan",
    "vanuatu": "vanuatu",
    "vaticaan": "vatican city",
    "vatikaan": "vatican city",
    "holy see": "vatican city",
    "venezuela": "venezuela",
    "vietnam": "vietnam",
    "jemen": "yemen",
    "zambia": "zambia",
    "zimbabwe": "zimbabwe",
}


def _fuzzy_find(query: str, country_list: list[dict]) -> dict | None:
    """Return the closest country by name using difflib, or None if no good match."""
    import difflib

    names = [str(c.get("name", "")).lower() for c in country_list]
    matches = difflib.get_close_matches(query, names, n=1, cutoff=0.6)
    if not matches:
        return None
    return next((c for c in country_list if str(c.get("name", "")).lower() == matches[0]), None)


def find_country(query: str, country_list: list[dict]) -> dict | None:
    """Find a country by code or name (case-insensitive, Dutch or English).

    Matching priority:
      1. Exact code match  (e.g. "NL", "CH")
      2. Exact name match or Dutch alias  (e.g. "Netherlands", "Nederland")
      3. Name starts-with
      4. Fuzzy match via difflib (handles typos)
    """
    q = query.strip().lower()
    # Resolve Dutch aliases and common alternatives
    q = _COUNTRY_ALIASES.get(q, q)

    hit = next((c for c in country_list if str(c.get("code", "")).lower() == q), None)
    if hit:
        return hit
    hit = next((c for c in country_list if str(c.get("name", "")).lower() == q), None)
    if hit:
        return hit
    hit = next((c for c in country_list if str(c.get("name", "")).lower().startswith(q)), None)
    if hit:
        return hit
    return _fuzzy_find(q, country_list)


def country_id(country: dict) -> str:
    """Return the best available ID for a country dict."""
    return str(
        country.get("_id")
        or country.get("id")
        or country.get("countryId")
        or country.get("code")
    )
